using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Project_Euler.Problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    ///1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    class Problem2_EvenFibonacciNumbers
    {
        public static int GetResult()
        {
            int iterations = 0;
            int sum = 0;
            int fib = 0;
            while(fib < 4000000)
            {
                fib = fibonacci(iterations);
                if(fib % 2 == 0)
                {
                    sum += fib;
                }
                iterations++;
            }
            return sum;
        }

        private static int fibonacci(int n)
        {
            int fib1 = 0;
            int fib2 = 1;

            for(int i = 0; i < n; i++)
            {
                int temp = fib1;
                fib1 = fib2;
                fib2 = temp + fib2;
            }
            return fib1;
        }
    }
}
